name: GCE Connect And Execute Script

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GCE_INSTANCE: test-run-jar	  
  GCE_INSTANCE_ZONE: asia-east2-a	
  
jobs:
  setup-pull-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    
    permissions:
      contents: 'read'
      id-token: 'write'
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - id: 'auth'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'
      
#     - id: 'auth'
#       uses: 'google-github-actions/auth@v0'
#       with:
#         workload_identity_provider: 'projects/123456789/locations/global/workloadIdentityPools/my-pool/providers/my-provider'
#         service_account: 'my-service-account@my-project.iam.gserviceaccount.com'
        
#     - name: GCP Github Action
#       uses: google-github-actions/setup-gcloud@master
#       with:
#           service_account_key: ${{ secrets.GCP_SA_KEY }}
#           project_id: ${{ secrets.GCP_PROJECT_ID }}
      
    - name: Connect GCE And execute docker ps
      run: |-
        gcloud compute ssh "$GCE_INSTANCE" --zone "$GCE_INSTANCE_ZONE" --
    - name: test docker
      run: docker ps
